### PR TITLE
staring initial immplementation of TC001

### PR DESCRIPTION
**Pull request by KalbinurK**

### CODE REVIEW

**Comment by LuisaFRojas** [comment]
Hey Akbar!
it looks good. there is always room for improvement. let's work as a group  to get there!

**Comment by KalbinurK** [comment]
Looks good to me

**Comment by KalbinurK** [comment]
lets have party here

**Comment by erfanjava** [comment]
so anyone can approve any merge request ?

**Comment by RajmiNakarmi** [comment]
Happy Hour... some how  i did today's task but still feel like i don't know anything.

**Pull request merged**
