### PR TITLE
Started initial implementation of test case 001

### PR DESCRIPTION
**Pull request by SF001User**
will add more commits after, let's merge it.

### CODE REVIEW

**Comment by erfanjava** [comment]
we can improve this code

**Comment by Fatime116** [comment]
seems like your codes need some improvement

**Comment by Fatime116** [comment]
you need add some useful method

**Comment by SF001User** [comment]
which part do you want to improve?

**Comment by erfanjava** [comment]
a java code without loop is not a java code

**Comment by erfanjava** [comment]
feels good

**Pull request merged**
